### ISSUE TITLE
K1 Arbeitsflächen schaffen

### ISSUE THREAD

**Issue by cccfr** [cccfr/cccfr-tuwat#11]
urgent, damit wir konkret Arbeitsplatz haben und Werkzeug nicht überall im Club rum marodiert

**Comment by viisauksena** [comment]
k1 wurde heute gereinigt und nicht gestrichen, aber so eingerichtet das man dort arbeiten kann und alles was da nicht reingehört rausgeworfen 
streichen und so fanden wir hier nicht nötig, bzw. darf agil wachsen, wie noch vieles in dem raum, aber der ist durchaus als benutzbar fertig 
die elektroverkabelung fehlt noch vollständig, man findet aber werkzeug, hat platz
