### ISSUE TITLE
Dekolichter speziell schalten

### ISSUE THREAD

**Issue by cccfr** [cccfr/cccfr-tuwat#12]
alle möglichen Lichter und Laser müssten speziell befestigt werden und könnten über angeschaffte Funksteckdosen im speziellen geschaltet werden.
Derzeit gibt es 2 Fernbedienungen und 10 Dosen.

Idee ist eine Fernbedieung mit einem Raspi(oder ähnlichem) zu verheiraten.
Danach 4 sinnvolle Gruppen bilden,
im Moment böte sich an :
1. Sound
2. Laser
3. Athmolichter
4. effekte mit Licht (Wassersäule u.ähnl.)

(ja sowas is Hackbar, happy birthday - du kannst das licht ein und auschalten , das du eh im club ein und ausschalten kannst) 
connect to @viisauksena

**Comment by viisauksena** [comment]
Fernsteuerung an Mischpult und oben im Schreibtisch
