### ISSUE TITLE
Banner außen hinhängen, Außenbeleuchtung und Klingel

### ISSUE THREAD

**Issue by cccfr** [cccfr/cccfr-tuwat#2]
- [ ] Banner ordentlich hinhängen, also Stabil und Nachhaltig
- [ ] ggf. Außenbeleuchtung fixen
- [ ] ggf. Klingel fixen

**Comment by ghost** [comment]
Ich fände eine IR-Sensor gesteuerte LED Lampe, die den Eingangs/Rampenbereich gut beleutet, sehr hilfreich.
