### ISSUE TITLE
Einen TTN Gateway aufstellen

### ISSUE THREAD

**Issue by sbamueller** [cccfr/cccfr-tuwat#27]
Ich würde mich ggf. darum kümmen, nach Kostenersatz.

**Comment by cccfr** [comment]
wir wissen erst ob wir hier gelder haben wenn wir überblick über unsere Umzugsausgaben haben.
Auch wieviele Mitglieder das hier tatsächlich verfolgen wollen spielt dabei eine Rolle.. 
wenn wir die selber bezahlen dauert das sicher noch 2 Monate bis wir mit dem Umzug soweit gesettelt sind und das jemand von uns ins Plenum bringt.

**Comment by sbamueller** [comment]
Ich habe jetzt einen RAK Wireless Gateway. Den würde ich gerne wo aufstellen (weil daheim mit dem anderen Gateway bringt er nix).
