### ISSUE TITLE
Es werde Licht! (im Hauptraum LEDs statt Röhren)

### ISSUE THREAD

**Issue by ghost** [cccfr/cccfr-tuwat#29]
Austausch der Leuchtstofflampen (mit all Ihren Nachteilen) durch LED-Strahler.
Phase 1:
 - Nutzung der vorhandenen Kabel/Bohrlöcher für schnelle Umsetzung.

Phase 2:
 - Anpassung an den konkreten Lichtbedarf (zB direkt/indirekt)

**Comment by ghost** [comment]
Es kamen 6 runde Strahler a 24W Dimmbar und 6 Eckige Fluter a 20W gestern in den Club.
Zwei runde Starhler wurden provisorisch (TM) montiert und an Kanal "B" (wie Beleuchtung) der Fernbedienung angeschlossen.

**Comment by ghost** [comment]
Es fehlt eine Leiter, die das Arbeiten an der hohen Decke ermöglicht (v.a. Abschrauben der aktuell vorhanden Leuchtstofflampenkästen.)
Daher: HELP WANTED

**Comment by ghost** [comment]
Wie soll das "dimmbar" realisiert werden? Wer kann hier durch Fachwissen unterstützen? Ich habe keine Ahnung von EIB/KNX usw.

**Comment by ghost** [comment]
Dimmervorschlag: https://www.pollin.de/p/dimmer-fuer-hutschiene-h-tronic-ds400-typ-b-532030
wird wie ein Stromstoßrelais verschaltet und mit einem Taster bedient.

**Comment by Raisouli** [comment]
Ja, was willst du damit dimmen?
Das ist ein Phasenschnitt Dimmer, dass muss vom Leuchtmittel unterstützt
sein, sonst geht das Leuchtmittel kaputt.
Welche dimmbare Leuchtmittel hast du den geholt? Marke? Modell?

eTc@cccfr.de <notifications@github.com> schrieb am Do., 22. März 2018,
19:35:

**Comment by ghost** [comment]
Die 6 runden Strahler sind lt. Datenblatt mit phasen-schnitt dimmbar.

**Comment by Raisouli** [comment]
Achso, dann klappt das.

eTc@cccfr.de <notifications@github.com> schrieb am Fr., 23. März 2018,
01:38:

**Comment by ghost** [comment]
Diese runden Strahler haben wir (6Stk. aktuell):
Decken-Einbauleuchte TOSHIBA LEDEUD00007C, GH76p-2, weiß 
Technische Daten:

    Betriebsspannung: 220...240 V~
    Sockel: GH76p-2
    Kompatible Lampentypen: Toshiba E-Core LED Light Engine
    Einbau-Ø: 140 mm
    Außen-Ø: 157 mm
    Einbau-Tiefe: 145 mm
    Farbe: weiß
    Schutzart: IP20
    Anwendungsbereich: Indoor
    Ausführung: fest
    Wieland Stecker-/Kupplung GST18I3S S1 ZR1 SW, mit Zugentlastung
    Material: Aluminium Strangpressprofil (Kühlkörper), Stahlblech pulverbeschichtet (Abdeckring)
    Gewicht: 1,5 kg
    Gesamtaße (HxØ): 113x157 mm 

Mit diesen Leuchtmitteln:
LED-Lampe TOSHIBA LEV162324M827TE, GH76p-2, EEK: A, 24 W, 1190 lm, 2700 K 
Datenblatt hierzu: https://www.pollin.de/productdownloads/D534262D.PDF
Technische Daten:

    Energieeffizienzklasse: A
    Gewichteter Energieverbrauch: 24 kWh/1000 h
    Betriebsspannung: 230 V
    Leistung: 24 W
    Sockel: GH76p-2
    Bauform: Reflektor
    Farbtemperatur: 2700 K
    Lichtfarbe: warmweiß
    Lichtstrom: 1190 lm
    Lichtausbeute: 49 lm/W
    Farbwiedergabeindex (CRI): > 80 Ra
    Abstrahlwinkel: 45°
    Dimmbar: ja (Phasenabschnittsdimmer)        <<<<<<<<<<<<<<<<<
    Mittlere Lebensdauer: 40.000 Stunden
    Schaltzyklen: > 12.500
    Lichtstromerhalt am Ende der Lebenszeit: 70 %
    Zündzeit: < 1 s
    Anlaufzeit bis 60 %: < 1 s
    Leistungsfaktor: 0,92
    Quecksilbergehalt: 0,0 mg
    Gewicht: 175 g
    Gesamtmaße (ØxL): 90x42 mm
