### ISSUE TITLE
Neumitglieder Handout, minibibel

### ISSUE THREAD

**Issue by cccfr** [cccfr/cccfr-tuwat#32]
oder wikiseite
da wo man sehen kann welchen email listen gibt es, 
wie ist die clubadresse,
wie hoch sind beiträge, bankdaten, 
wer ist für welches infrastruktur-projekt "zuständig"/ansprechbar
wann ist mülltag
was sind so wiederkehrende jahreshighlights
infrastrukturmanifest
keymemberregeln - öffnungsregeln
startup und shutdown im club - alles an/aus, wie geht das
cert contacts

**Comment by showmetheworld** [comment]
war auf der tuwat auch Thema. im Dokuwiki gibt's unter den Stichpunkten Bildung & WelcomePatterns einen entsprechenden Ansatz an dem frau/man sich orientieren könnte.
+1 für Wikiseite

**Comment by sbamueller** [comment]
Ich würde vorschlagen einen Flyer zu machen mit allgemeinen Infos über den CCC fr:
- Wo trifft der sich
- Was macht der
- Ziele
- muß ich ein krasser Hacker sein um Mitglied zu werden
- Angebote
- Wie werde ich Mitglied
- Projekte

Das so wie unser TTN Flyer, A4 Doppelseite, 3x gefaltet. kostet 1000 Stück ca 60 EUR. Net formatiert, mit Bildern

UUUUUUUnd: dazu die sogenante Hackerbibel, die sich ja eher an Interessierte bzw. Mitglieder wendet. Die würde ich irgendwie “online” machen, oder zum ausdrucken, für die Leute zum lesen, wenn sie interessierter sind.

Flyer kann ich nach Apsprache gerne entwerfen. Leider geht mein Adobe InDesign nicht mehr, nach mac update und daher nutze ich dafür derzeit Pages (auch wenn ich jetzt wahrscheinlich in die Open Source Hölle komme), aber die Ergebenisse sind ganz passabel.
