### ISSUE TITLE
Küche auf die Linke Seite bringen

### ISSUE THREAD

**Issue by cccfr** [cccfr/cccfr-tuwat#4]
_wuschl

Küche soll auf die Linke Seite an die Wand

- [ ] dummy
- [ ]  dummy
- [ ]  dummy

**Comment by wuschl** [comment]
Ich weiß nicht wie ich zu der Ehre komme, aber ich fürchte ich kann nur schwer helfen. :-)

Grüße aus Österreich

**Comment by viisauksena** [comment]
das is ja lustig, ne das sollte kein autolink werden, aber grüße auch zurück

**Comment by cccfr** [comment]
Hab ich nicht erwähnt, daß ich keinen Github-Account hab?

@

**Comment by viisauksena** [comment]
jetzt haste ja doch einen :) 
könntest die aufgabe mit leben füllen

**Comment by cccfr** [comment]
close dummy, need more specific tasks
