### ISSUE TITLE
K2 - Elab reinigen und streichen

### ISSUE THREAD

**Issue by cccfr** [cccfr/cccfr-tuwat#5]
leer räumen und streichen

**Comment by ghost** [comment]
akueller Zustand eher staublastig, daher

    Boden mit "Garagenfarbe" streichen, eventuell mit Antistatik-Beimischengen?
    Wände normal Streichen (der Optik wegen)
    Decke (dünn! = 0,5cm max) Verputzen?! Oder Streichen? Vorher verspachteln?

**Comment by viisauksena** [comment]
Decke fehlt noch, 
Boden optional - wenn man später bedarf dazu sieht

**Comment by ghost** [comment]
Aufrung der Regalmontage wird die Decke wohl auch nicht fertig gestrichen. Es fehlte nach dem Wändestreichen an Farbe.

Somit ist dieser Punkt abgeschlossen. / Schliesse das Issue.
