### ISSUE TITLE
Leergut wegbringen, neue Vorräte besorgen

### ISSUE THREAD

**Issue by cccfr** [cccfr/cccfr-tuwat#7]
leergut weg bringen , ca 12 Kisten 
(alles was nicht Premium Bier/Cola ist)

und neue Dinge holen
Bier/Mate - bitte kein Rotz besorgen :)

**Comment by viisauksena** [comment]
Bestellung bei Premium heute (7.3.2018) gemacht , betrifft hier nur die Premium Kisten
Cola ist noch da, Bier wird nochmal kommen, und auch einige Flaschen Sekt, der ist zwar "relativ" teuer, aber extrem gut

**Comment by cccfr** [comment]
done

**Comment by ghost** [comment]
Reopened. :)

Subject: [Intern] seriöse Getränketour bald nötig
Date: 2018-03-21 11:47

steht bald an, im Moment sind noch 3 Kisten Mate und 2 Kisten Bier und
reste Spezi da, aber imjetzigen Tempo verdunstet das eher ...
da stehen auch 12 leere Kästen (von denen 3 wegs Premiem bleiben).

Falls also wer mal mit Geld und Auto einkaufen fährt.

nicht das es zur Matekalypse kommt, oder das Bier mal ausgeht

;)
